(function(){"use strict";
const STORAGE_KEY="cortex_pmpe_2026";
const SUBJECTS=[
{key:"portugues",name:"Língua Portuguesa",block:"Bloco I",topics:[
"Compreensão e interpretação de textos","Tipologias e gêneros textuais","Figuras de linguagem","Relações semânticas: oposição, conclusão, concessão, causalidade, adição e alternância","Ortografia oficial","Acentuação gráfica","Emprego das classes de palavras","Emprego do sinal indicativo de crase","Sintaxe da oração e do período","Funções do “que” e do “se”","Mecanismos de coesão textual","Emprego dos sinais de pontuação","Concordância nominal e verbal","Regência nominal e verbal","Colocação pronominal","Processos de formação de palavras","Significação das palavras","Variação linguística"]},
{key:"historia",name:"História de Pernambuco",block:"Bloco I",topics:[
"Ocupação e colonização: contatos iniciais, capitanias hereditárias e Duarte Coelho","Importância do açúcar para a economia local","Formação de Olinda e Recife","Presença holandesa e governo de Maurício de Nassau","Resistência e movimentos emancipacionistas: quilombos, Insurreição, Mascates, 1817, Equador, Cabanos e Praieira","Pernambuco durante o período republicano","Cultura popular pernambucana: frevo, maracatu, culinária e festas","Aspectos afro-brasileiros em Pernambuco"]},
{key:"rlm",name:"Raciocínio Lógico",block:"Bloco II",topics:[
"Estruturas lógicas: proposições, conectivos, quantificadores e falácias","Lógica de argumentação: analogias, inferências, deduções, equivalência e implicação","Diagramas lógicos","Contagem: princípio multiplicativo, permutações, arranjos, combinações e probabilidade"]},
{key:"informatica",name:"Informática",block:"Bloco II",topics:[
"Internet e intranet","Navegadores, serviços de internet e computação em nuvem","Segurança da informação: ameaças, malwares, phishing, criptografia e autenticação","Armazenamento, backup e restauração de dados","Arquivos, pastas, programas e organização de computadores/periféricos","Windows 11: arquivos, configurações, Painel de Controle e Prompt de Comando","Office 2019 e LibreOffice 7: Word/Writer, Excel/Calc e PowerPoint/Impress"]},
{key:"constitucional",name:"Direito Constitucional",block:"Bloco III",topics:[
"Princípios fundamentais","Direitos e garantias fundamentais, direitos sociais, nacionalidade, direitos políticos e remédios constitucionais","Organização do Estado, competências, Administração Pública, servidores e militares estaduais","Organização dos Poderes e Funções Essenciais à Justiça","Defesa do Estado e das instituições democráticas","Súmulas, jurisprudência dominante e legislação relacionada"]},
{key:"dh",name:"Direitos Humanos e Legislação Extravagante",block:"Bloco III",topics:[
"Teoria geral dos direitos humanos","Evolução histórica e gerações de direitos humanos","Tratados internacionais de direitos humanos e CF art. 5º §§2º e 3º","Declaração Universal dos Direitos Humanos","Convenção Americana de Direitos Humanos — Pacto de San José","ECA — Lei 8.069/1990: pontos pertinentes à atividade policial","Lei 13.869/2019 — Abuso de Autoridade","Lei 9.455/1997 — Tortura","Lei 11.340/2006 — Maria da Penha","Lei 7.716/1989 — Crimes de preconceito de raça ou cor","Lei 9.605/1998 — Crimes ambientais","Lei 8.072/1990 — Crimes hediondos","Lei 11.343/2006 — Drogas","Lei Estadual 6.783/1974 — Estatuto dos Policiais Militares de Pernambuco","Lei 10.741/2003 — Estatuto da Pessoa Idosa","Lei 12.852/2013 — Estatuto da Juventude","Súmulas, jurisprudência dominante e legislação relacionada"]}];


window.PMPE_SUBJECTS=SUBJECTS;

const LAW_LINKS={
"Tratados internacionais de direitos humanos e CF art. 5º §§2º e 3º":"https://www.planalto.gov.br/ccivil_03/constituicao/constituicao.htm",
"Declaração Universal dos Direitos Humanos":"https://www.unicef.org/brazil/declaracao-universal-dos-direitos-humanos",
"Convenção Americana de Direitos Humanos — Pacto de San José":"https://www.planalto.gov.br/ccivil_03/decreto/d0678.htm",
"ECA — Lei 8.069/1990: pontos pertinentes à atividade policial":"https://www.planalto.gov.br/ccivil_03/leis/l8069.htm",
"Lei 13.869/2019 — Abuso de Autoridade":"https://www.planalto.gov.br/ccivil_03/_ato2019-2022/2019/lei/l13869.htm",
"Lei 9.455/1997 — Tortura":"https://www.planalto.gov.br/ccivil_03/leis/l9455.htm",
"Lei 11.340/2006 — Maria da Penha":"https://www.planalto.gov.br/ccivil_03/_ato2004-2006/2006/lei/l11340.htm",
"Lei 7.716/1989 — Crimes de preconceito de raça ou cor":"https://www.planalto.gov.br/ccivil_03/leis/l7716.htm",
"Lei 9.605/1998 — Crimes ambientais":"https://www.planalto.gov.br/ccivil_03/leis/l9605.htm",
"Lei 8.072/1990 — Crimes hediondos":"https://www.planalto.gov.br/ccivil_03/leis/l8072.htm",
"Lei 11.343/2006 — Drogas":"https://www.planalto.gov.br/ccivil_03/_ato2004-2006/2006/lei/l11343.htm",
"Lei 10.741/2003 — Estatuto da Pessoa Idosa":"https://www.planalto.gov.br/ccivil_03/leis/2003/l10.741.htm",
"Lei 12.852/2013 — Estatuto da Juventude":"https://www.planalto.gov.br/ccivil_03/_ato2011-2014/2013/lei/l12852.htm",
"Princípios fundamentais":"https://www.planalto.gov.br/ccivil_03/constituicao/constituicao.htm",
"Direitos e garantias fundamentais, direitos sociais, nacionalidade, direitos políticos e remédios constitucionais":"https://www.planalto.gov.br/ccivil_03/constituicao/constituicao.htm",
"Organização do Estado, competências, Administração Pública, servidores e militares estaduais":"https://www.planalto.gov.br/ccivil_03/constituicao/constituicao.htm",
"Organização dos Poderes e Funções Essenciais à Justiça":"https://www.planalto.gov.br/ccivil_03/constituicao/constituicao.htm",
"Defesa do Estado e das instituições democráticas":"https://www.planalto.gov.br/ccivil_03/constituicao/constituicao.htm"};

const SPECIAL={
rlm:"https://profrafaelcardoso.com.br/pm-pe/raio-x-aocp/",
constitucional:"https://escola.mpu.mp.br/plataforma-aprender/acervo-educacional/conteudo/direito-constitucional-modulo-1-teoria-da-constituicao",
historia:"https://www.pm.pe.gov.br/historico/"
};

let state=loadState(),activeFilter="all",searchTerm="";
function normalizeSearch(value){return String(value||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g," ").trim();}
function topicMatchesSearch(subject,topic){if(!searchTerm)return true;const aliases={portugues:"lingua portuguesa gramatica",historia:"historia pernambuco pmpe",rlm:"raciocinio logico matematica logica",informatica:"computacao windows office internet",constitucional:"direito constitucional constituicao cf88",dh:"direitos humanos legislacao leis"};const haystack=normalizeSearch([subject.name,subject.block,subject.key,topic,aliases[subject.key]||"",LAW_LINKS[topic]?"lei legislacao norma":"",SPECIAL[subject.key]?"material aula":""] .join(" "));const terms=normalizeSearch(searchTerm).split(" ").filter(Boolean);return terms.every(term=>haystack.includes(term));}
function loadState(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||"{}")||{};}catch(e){return {};}}
function saveState(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(state));}catch(e){}}
function topicKey(s,i){return s.key+":"+i;}
function getTopicState(key){return state[key]||{};}
function toggle(key,field){const next={...getTopicState(key)};next[field]=!next[field];state[key]=next;state.last=key;saveState();render();}
function qSearch(subject,topic){return "https://www.youtube.com/results?search_query="+encodeURIComponent("PMPE 2026 "+subject+" "+topic+" Instituto AOCP aula");}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));}
function renderFilters(){const el=document.getElementById("pmpeFilters");el.innerHTML=[["all","Todas"],...SUBJECTS.map(s=>[s.key,s.name])].map(([k,n])=>'<button type="button" data-filter="'+k+'" class="'+(activeFilter===k?"active":"")+'">'+esc(n)+'</button>').join("");el.querySelectorAll("button").forEach(b=>b.addEventListener("click",()=>{activeFilter=b.dataset.filter;render();}));}
function render(){
renderFilters();
const host=document.getElementById("pmpeSubjects");let visible=0;
host.innerHTML=SUBJECTS.filter(s=>activeFilter==="all"||s.key===activeFilter).map((s,si)=>{
const rows=s.topics.map((topic,i)=>{const key=topicKey(s,i),t=getTopicState(key);const match=topicMatchesSearch(s,topic);if(!match)return "";visible++;const law=LAW_LINKS[topic];return '<article class="pmpe-topic '+(t.studied?"complete":"")+'" data-topic-key="'+key+'"><div class="pmpe-topic-index">'+String(i+1).padStart(2,"0")+'</div><div><h3>'+esc(topic)+'</h3><p>'+esc(s.block)+' · tópico '+(i+1)+' de '+s.topics.length+'</p><div class="pmpe-topic-links"><a href="'+qSearch(s.name,topic)+'" target="_blank" rel="noopener">Aula gratuita</a><button type="button" class="pmpe-topic-question-link" data-topic-question="'+key+'">Questões AOCP</button>'+(SPECIAL[s.key]?'<a href="'+SPECIAL[s.key]+'" target="_blank" rel="noopener">Material selecionado</a>':"")+(law?'<a href="'+law+'" target="_blank" rel="noopener">Lei seca</a>':"")+'</div></div><div class="pmpe-topic-actions"><button type="button" data-action="studied" class="pmpe-status-btn done '+(t.studied?"active":"")+'"><span class="pmpe-status-icon">'+(t.studied?"✓":"○")+'</span><span>'+(t.studied?"Concluído":"Marcar como concluído")+'</span></button><button type="button" data-action="reviewed" class="pmpe-status-btn review '+(t.reviewed?"active":"")+'"><span class="pmpe-status-icon">'+(t.reviewed?"★":"↻")+'</span><span>'+(t.reviewed?"Marcado para revisar":"Revisar depois")+'</span></button></div></article>';}).join("");
const completed=s.topics.filter((_,i)=>getTopicState(topicKey(s,i)).studied).length;const pct=Math.round(completed/s.topics.length*100);if(!rows)return "";
return '<section class="pmpe-subject '+((activeFilter===s.key||searchTerm)?"open":"")+'" data-subject="'+s.key+'"><div class="pmpe-subject-head"><div class="pmpe-subject-badge">'+(si+1)+'</div><div class="pmpe-subject-copy"><strong>'+esc(s.name)+'</strong><small>'+esc(s.block)+' · '+s.topics.length+' tópicos · '+completed+' concluídos</small></div><div class="pmpe-subject-progress"><i style="width:'+pct+'%"></i></div><div class="pmpe-subject-toggle">⌄</div></div><div class="pmpe-topic-list">'+rows+'</div></section>';}).join("")||'<div class="pmpe-empty">Nenhum tópico encontrado.</div>';
host.querySelectorAll(".pmpe-subject-head").forEach(h=>h.addEventListener("click",e=>{if(e.target.closest("a,button"))return;h.parentElement.classList.toggle("open");}));
host.querySelectorAll("[data-action]").forEach(b=>b.addEventListener("click",()=>{const key=b.closest(".pmpe-topic").dataset.topicKey;toggle(key,b.dataset.action);}));host.querySelectorAll("[data-topic-question]").forEach(b=>b.addEventListener("click",()=>{if(typeof window.PMPEOpenQuestions==="function")window.PMPEOpenQuestions(b.dataset.topicQuestion);}));
document.getElementById("pmpeVisibleCount").textContent=visible+" tópicos";updateStats();
}
function updateStats(){let studied=0,reviewed=0,questions=0,total=0;SUBJECTS.forEach(s=>s.topics.forEach((_,i)=>{total++;const t=getTopicState(topicKey(s,i));if(t.studied)studied++;if(t.reviewed)reviewed++;if(t.questions)questions++;}));const pct=Math.round(studied/total*100);document.getElementById("pmpeProgressValue").textContent=pct+"%";document.getElementById("pmpeProgressText").textContent=studied+" de "+total+" tópicos";document.getElementById("pmpeStudied").textContent=studied;document.getElementById("pmpeReviewed").textContent=reviewed;document.getElementById("pmpeQuestions").textContent=questions;}
function countdown(){const exam=new Date("2027-02-21T08:00:00-03:00"),now=new Date(),days=Math.max(0,Math.ceil((exam-now)/86400000));document.getElementById("pmpeCountdown").textContent=days+" dias";}
document.getElementById("pmpeSearch").addEventListener("input",e=>{searchTerm=e.target.value.trim();render();});
document.getElementById("pmpeResumeBtn").addEventListener("click",()=>{if(!state.last){document.querySelector(".pmpe-course").scrollIntoView({behavior:"smooth"});return;}const subject=state.last.split(":")[0];activeFilter=subject;searchTerm="";document.getElementById("pmpeSearch").value="";render();setTimeout(()=>{const el=document.querySelector('[data-topic-key="'+CSS.escape(state.last)+'"]');if(el)el.scrollIntoView({behavior:"smooth",block:"center"});},50);});
countdown();render();
})();

(function(){"use strict";
const SUBJECTS=window.PMPE_SUBJECTS||[];
const QSTORE="cortex_pmpe_2026_questions";
const PORT_TEXT=`Em uma manhã de segunda-feira, a central de operações recebeu sucessivas chamadas sobre um alagamento que interrompia o trânsito em uma avenida do Recife. Embora a chuva tivesse diminuído, equipes permaneciam no local, pois a água ainda avançava sobre as faixas mais baixas da via. Moradores relatavam que, em anos anteriores, o problema desaparecia poucas horas depois; naquele dia, porém, o escoamento seguia lento. A Defesa Civil orientou os condutores a evitar a região e informou que novas avaliações seriam feitas ao longo da manhã.`;

const BANK=[
{id:"portugues:0",subject:"portugues",subjectName:"Língua Portuguesa",topicIndex:0,topic:SUBJECTS[0].topics[0],source:"Autoral Cortex · padrão AOCP/PMPE",context:PORT_TEXT,prompt:"A partir das informações do texto, assinale a alternativa correta.",options:["A interrupção do trânsito ocorreu exclusivamente porque a chuva continuava intensa.","O texto informa que o alagamento já havia sido totalmente resolvido antes da chegada das equipes.","O escoamento da água apresentava comportamento diferente daquele relatado pelos moradores em anos anteriores.","A Defesa Civil determinou a interdição definitiva da avenida.","Os moradores afirmaram que o problema nunca havia ocorrido anteriormente."],answer:2,explanation:"O texto contrapõe o escoamento rápido de anos anteriores ao escoamento lento observado naquele dia."},
{id:"portugues:1",subject:"portugues",subjectName:"Língua Portuguesa",topicIndex:1,topic:SUBJECTS[0].topics[1],source:"Autoral Cortex · padrão AOCP/PMPE",context:PORT_TEXT,prompt:"Quanto à organização predominante do texto, assinale a alternativa correta.",options:["Predomina a injunção, pois o texto se organiza integralmente em ordens ao leitor.","Predomina a narração de um fato real, com informações objetivas sobre uma ocorrência urbana.","Predomina a descrição literária, com ênfase em impressões subjetivas do narrador.","Predomina a argumentação, pois há defesa explícita de uma tese sobre planejamento urbano.","Predomina o diálogo, uma vez que as falas dos moradores estruturam o texto."],answer:1,explanation:"O texto relata uma ocorrência em sequência temporal e apresenta informações factuais, com traços expositivos."},
{id:"portugues:2",subject:"portugues",subjectName:"Língua Portuguesa",topicIndex:2,topic:SUBJECTS[0].topics[2],source:"Autoral Cortex · padrão AOCP/PMPE",context:"No trecho: “a água ainda avançava sobre as faixas mais baixas da via”, considere a substituição por “a água engolia lentamente as faixas mais baixas da via”.",prompt:"A alteração introduz, principalmente, qual figura de linguagem?",options:["Metonímia.","Eufemismo.","Personificação.","Pleonasmo.","Antítese."],answer:2,explanation:"Atribui-se à água uma ação própria de ser animado, configurando personificação."},
{id:"portugues:3",subject:"portugues",subjectName:"Língua Portuguesa",topicIndex:3,topic:SUBJECTS[0].topics[3],source:"Autoral Cortex · padrão AOCP/PMPE",context:PORT_TEXT,prompt:"No trecho “Embora a chuva tivesse diminuído, equipes permaneciam no local, pois a água ainda avançava...”, as expressões destacadas estabelecem, respectivamente, relações de",options:["causa e consequência.","concessão e causa.","condição e conclusão.","oposição e finalidade.","conformidade e explicação."],answer:1,explanation:"“Embora” introduz concessão; “pois”, no contexto, apresenta a causa da permanência das equipes."},
{id:"portugues:4",subject:"portugues",subjectName:"Língua Portuguesa",topicIndex:4,topic:SUBJECTS[0].topics[4],source:"Autoral Cortex · padrão AOCP/PMPE",prompt:"Assinale a alternativa em que todas as palavras estão grafadas de acordo com a ortografia oficial.",options:["exceção – empecilho – privilégio – beneficiente","exceção – empecilho – privilégio – beneficente","excessão – impecilho – previlégio – beneficente","exceção – impecilho – privilégio – beneficiente","excessão – empecilho – previlégio – beneficente"],answer:1,explanation:"A grafia correta é exceção, empecilho, privilégio e beneficente."},
{id:"portugues:5",subject:"portugues",subjectName:"Língua Portuguesa",topicIndex:5,topic:SUBJECTS[0].topics[5],source:"Autoral Cortex · padrão AOCP/PMPE",prompt:"Assinale a alternativa em que a palavra é acentuada pela mesma regra que “trânsito”.",options:["saída.","também.","público.","país.","você."],answer:2,explanation:"“Trânsito” e “público” são proparoxítonas, e todas as proparoxítonas são acentuadas."},
{id:"portugues:6",subject:"portugues",subjectName:"Língua Portuguesa",topicIndex:6,topic:SUBJECTS[0].topics[6],source:"Autoral Cortex · padrão AOCP/PMPE",context:"Considere: “Moradores relatavam que, em anos anteriores, o problema desaparecia poucas horas depois.”",prompt:"No período apresentado, a palavra “que” classifica-se como",options:["pronome relativo, retomando “moradores”.","conjunção integrante, introduzindo oração subordinada substantiva.","preposição acidental.","pronome indefinido.","conjunção coordenativa explicativa."],answer:1,explanation:"O “que” introduz o conteúdo do verbo “relatavam”, funcionando como conjunção integrante."},
{id:"portugues:7",subject:"portugues",subjectName:"Língua Portuguesa",topicIndex:7,topic:SUBJECTS[0].topics[7],source:"Autoral Cortex · padrão AOCP/PMPE",prompt:"Assinale a alternativa em que o emprego do acento indicativo de crase está correto.",options:["A equipe chegou à Recife antes das seis horas.","Os agentes ficaram frente à frente durante a orientação.","A Defesa Civil fez referência àquela área de risco.","O aviso foi entregue à todos os moradores.","Os veículos retornaram à partir das dez horas."],answer:2,explanation:"Em “àquela”, ocorre a fusão da preposição “a” com o pronome demonstrativo “aquela”."},
{id:"portugues:8",subject:"portugues",subjectName:"Língua Portuguesa",topicIndex:8,topic:SUBJECTS[0].topics[8],source:"Autoral Cortex · padrão AOCP/PMPE",context:"“A Defesa Civil orientou os condutores a evitar a região e informou que novas avaliações seriam feitas.”",prompt:"A oração “que novas avaliações seriam feitas” exerce função sintática de",options:["objeto direto de “informou”.","sujeito de “informou”.","adjunto adverbial de causa.","complemento nominal de “Defesa Civil”.","oração coordenada explicativa."],answer:0,explanation:"O conteúdo introduzido por “que” completa diretamente o sentido do verbo “informou”."},
{id:"portugues:9",subject:"portugues",subjectName:"Língua Portuguesa",topicIndex:9,topic:SUBJECTS[0].topics[9],source:"Autoral Cortex · padrão AOCP/PMPE",prompt:"Analise os usos de “se”: I. Divulgaram-se as rotas alternativas. II. Se a água subir, a avenida será interditada. III. O agente perguntou se havia feridos. Assinale a alternativa que apresenta, respectivamente, a classificação correta.",options:["índice de indeterminação do sujeito – conjunção integrante – pronome reflexivo.","partícula apassivadora – conjunção condicional – conjunção integrante.","pronome reflexivo – conjunção concessiva – partícula apassivadora.","partícula expletiva – conjunção causal – pronome relativo.","índice de indeterminação do sujeito – conjunção condicional – pronome reflexivo."],answer:1,explanation:"Em I, há voz passiva sintética; em II, condição; em III, oração subordinada substantiva interrogativa indireta."},
{id:"portugues:10",subject:"portugues",subjectName:"Língua Portuguesa",topicIndex:10,topic:SUBJECTS[0].topics[10],source:"Autoral Cortex · padrão AOCP/PMPE",context:PORT_TEXT,prompt:"No trecho “naquele dia, porém, o escoamento seguia lento”, o termo “porém” contribui para a coesão ao estabelecer relação de",options:["explicação.","conclusão.","oposição.","causa.","condição."],answer:2,explanation:"“Porém” é conjunção adversativa, marcando contraste com a situação relatada anteriormente."},
{id:"portugues:11",subject:"portugues",subjectName:"Língua Portuguesa",topicIndex:11,topic:SUBJECTS[0].topics[11],source:"Autoral Cortex · padrão AOCP/PMPE",prompt:"Assinale a alternativa em que a vírgula foi empregada de acordo com a norma-padrão.",options:["As equipes de resgate, permaneceram na avenida.","Quando a chuva diminuiu, os agentes iniciaram nova vistoria.","A Defesa Civil informou que, novas avaliações seriam feitas.","Os moradores, que chegaram cedo solicitaram orientação.","O trânsito foi desviado porque, a pista estava alagada."],answer:1,explanation:"A vírgula separa corretamente a oração subordinada adverbial anteposta."},
{id:"portugues:12",subject:"portugues",subjectName:"Língua Portuguesa",topicIndex:12,topic:SUBJECTS[0].topics[12],source:"Autoral Cortex · padrão AOCP/PMPE",prompt:"Assinale a alternativa que está de acordo com a norma-padrão de concordância.",options:["Fazem duas horas que as equipes chegaram.","Houveram diversos chamados durante a manhã.","Devem existir rotas alternativas para a região.","Foi identificado muitas áreas de risco.","Segue anexas as orientações da Defesa Civil."],answer:2,explanation:"Com “existir”, o verbo flexiona normalmente: “devem existir rotas”."},
{id:"portugues:13",subject:"portugues",subjectName:"Língua Portuguesa",topicIndex:13,topic:SUBJECTS[0].topics[13],source:"Autoral Cortex · padrão AOCP/PMPE",prompt:"Assinale a alternativa correta quanto à regência verbal prescrita pela norma-padrão.",options:["Os moradores assistiram o trabalho das equipes.","Os agentes obedeceram o protocolo de segurança.","A população foi informada de que a via seria interditada.","O condutor preferiu desviar do que aguardar.","A equipe visava a redução dos riscos, no sentido de “almejar”."],answer:2,explanation:"“Informar alguém de algo” é construção admitida. Nas demais, há problemas de regência no contexto apresentado."},
{id:"portugues:14",subject:"portugues",subjectName:"Língua Portuguesa",topicIndex:14,topic:SUBJECTS[0].topics[14],source:"Autoral Cortex · padrão AOCP/PMPE",prompt:"Assinale a alternativa em que a colocação pronominal atende à norma-padrão.",options:["Me avisaram sobre a interdição ontem.","Nunca disseram-me que a via seria fechada.","Quando aproximou-se da barreira, o condutor reduziu a velocidade.","Não se identificaram novos pontos de alagamento.","A equipe tinha deslocado-se antes do amanhecer."],answer:3,explanation:"A palavra negativa “não” atrai o pronome para próclise: “não se identificaram”."},
{id:"portugues:15",subject:"portugues",subjectName:"Língua Portuguesa",topicIndex:15,topic:SUBJECTS[0].topics[15],source:"Autoral Cortex · padrão AOCP/PMPE",prompt:"A palavra “desnecessário” é formada, predominantemente, por",options:["composição por justaposição.","derivação prefixal e sufixal.","derivação regressiva.","composição por aglutinação.","abreviação vocabular."],answer:1,explanation:"Há acréscimo de prefixo e sufixo à base lexical."},
{id:"portugues:16",subject:"portugues",subjectName:"Língua Portuguesa",topicIndex:16,topic:SUBJECTS[0].topics[16],source:"Autoral Cortex · padrão AOCP/PMPE",context:"No trecho “a água ainda avançava sobre as faixas mais baixas da via”, a palavra “faixas” refere-se às porções destinadas ao tráfego de veículos.",prompt:"Nesse contexto, o sentido da palavra “faixas” exemplifica",options:["polissemia, pois a palavra possui outros sentidos possíveis em diferentes contextos.","antonímia, pois se opõe ao sentido de “via”.","paronímia, pois se aproxima graficamente de “fachas”.","eufemismo, pois suaviza uma informação negativa.","hiperonímia obrigatória."],answer:0,explanation:"“Faixa” pode assumir diferentes sentidos; o contexto seleciona o sentido de faixa de circulação."},
{id:"portugues:17",subject:"portugues",subjectName:"Língua Portuguesa",topicIndex:17,topic:SUBJECTS[0].topics[17],source:"Autoral Cortex · padrão AOCP/PMPE",prompt:"Sobre variação linguística, assinale a alternativa correta.",options:["Toda variedade regional constitui erro gramatical.","A norma-padrão elimina as demais variedades da língua.","A adequação linguística depende também da situação comunicativa e do interlocutor.","A fala coloquial é invariavelmente inadequada em qualquer contexto.","Variação histórica e variação social são fenômenos inexistentes na língua portuguesa."],answer:2,explanation:"A língua varia historicamente, regionalmente e socialmente, e a escolha da variedade depende do contexto de uso."},

{id:"historia:0",subject:"historia",subjectName:"História de Pernambuco",topicIndex:0,topic:SUBJECTS[1].topics[0],source:"Autoral Cortex · materiais PMPE + padrão AOCP",prompt:"No processo de colonização portuguesa, a Capitania de Pernambuco destacou-se entre as capitanias hereditárias. A respeito desse processo, assinale a alternativa correta.",options:["Pernambuco foi doada a Tomé de Sousa, que implantou o Governo-Geral na capitania.","Duarte Coelho recebeu a capitania e teve papel central na organização inicial do povoamento e da produção açucareira.","A colonização efetiva de Pernambuco começou em 1500, imediatamente após a chegada de Cabral.","A capitania foi economicamente irrelevante durante todo o século XVI.","O sistema de capitanias transferia à Coroa toda a responsabilidade direta pelo povoamento, sem participação dos donatários."],answer:1,explanation:"Duarte Coelho foi o donatário de Pernambuco e sua atuação está ligada ao povoamento e ao desenvolvimento açucareiro."},
{id:"historia:1",subject:"historia",subjectName:"História de Pernambuco",topicIndex:1,topic:SUBJECTS[1].topics[1],source:"Autoral Cortex · materiais PMPE + padrão AOCP",prompt:"Sobre a economia açucareira em Pernambuco nos séculos XVI e XVII, analise as assertivas: I. A produção açucareira contribuiu para a projeção econômica da capitania. II. A atividade esteve ligada ao sistema de engenhos e ao comércio atlântico. III. A importância do açúcar impediu crises e oscilações econômicas ao longo do período. Assinale a alternativa correta.",options:["Apenas I.","Apenas III.","Apenas I e II.","Apenas II e III.","I, II e III."],answer:2,explanation:"I e II são corretas. A dependência do açúcar não eliminou crises nem oscilações."},
{id:"historia:2",subject:"historia",subjectName:"História de Pernambuco",topicIndex:2,topic:SUBJECTS[1].topics[2],source:"Autoral Cortex · materiais PMPE + padrão AOCP",prompt:"A respeito da formação histórica de Olinda e Recife, assinale a alternativa correta.",options:["Recife nasceu como centro agrário distante do litoral, enquanto Olinda se desenvolveu em torno do porto.","Olinda esteve vinculada à elite açucareira, enquanto Recife ganhou importância como núcleo portuário e comercial.","As duas cidades tiveram origem exclusivamente durante o domínio holandês.","Olinda foi fundada apenas no século XVIII, após a Guerra dos Mascates.","Recife permaneceu sem relevância comercial até o século XX."],answer:1,explanation:"Olinda se consolidou como centro da elite açucareira; Recife cresceu ligado ao porto e ao comércio."},
{id:"historia:3",subject:"historia",subjectName:"História de Pernambuco",topicIndex:3,topic:SUBJECTS[1].topics[3],source:"Autoral Cortex · materiais PMPE + padrão AOCP",prompt:"A presença neerlandesa em Pernambuco marcou profundamente o século XVII. Assinale a alternativa INCORRETA.",options:["A invasão holandesa em Pernambuco ocorreu em 1630.","A Companhia das Índias Ocidentais tinha interesses ligados ao açúcar e ao comércio atlântico.","Maurício de Nassau governou parte do Brasil holandês entre 1637 e 1644.","A Insurreição Pernambucana contribuiu para o fim do domínio holandês.","Maurício de Nassau governou Pernambuco após a expulsão definitiva dos holandeses, entre 1654 e 1664."],answer:4,explanation:"Nassau governou durante o período holandês, antes da expulsão de 1654."},
{id:"historia:4",subject:"historia",subjectName:"História de Pernambuco",topicIndex:4,topic:SUBJECTS[1].topics[4],source:"Autoral Cortex · materiais PMPE + padrão AOCP",prompt:"Relacione os movimentos pernambucanos às respectivas características: I. Guerra dos Mascates. II. Revolução Pernambucana de 1817. III. Confederação do Equador. IV. Revolução Praieira. Assinale a alternativa correta.",options:["I – conflito entre Olinda e Recife; II – movimento republicano; III – reação ao centralismo imperial; IV – movimento liberal do século XIX.","I – revolta escrava; II – defesa da monarquia portuguesa; III – movimento pró-centralização; IV – invasão holandesa.","I – movimento de 1824; II – revolta de 1710; III – movimento de 1848; IV – revolta de 1817.","Todos ocorreram durante o período colonial.","Apenas II e IV tiveram qualquer relação com ideias republicanas ou liberais."],answer:0,explanation:"A sequência corresponde às características centrais desses movimentos."},
{id:"historia:5",subject:"historia",subjectName:"História de Pernambuco",topicIndex:5,topic:SUBJECTS[1].topics[5],source:"Autoral Cortex · materiais PMPE + padrão AOCP",prompt:"No período republicano, Pernambuco atravessou diferentes conjunturas políticas e sociais. Assinale a alternativa correta.",options:["A história republicana pernambucana foi politicamente uniforme, sem movimentos sociais relevantes.","As Ligas Camponesas tiveram importância nas mobilizações sociais do estado no século XX.","Pernambuco não sofreu efeitos do regime militar instaurado em 1964.","A redemocratização brasileira não alterou a dinâmica política estadual.","A Era Vargas não produziu impactos institucionais em Pernambuco."],answer:1,explanation:"As Ligas Camponesas foram parte importante da mobilização social pernambucana no século XX."},
{id:"historia:6",subject:"historia",subjectName:"História de Pernambuco",topicIndex:6,topic:SUBJECTS[1].topics[6],source:"Autoral Cortex · materiais PMPE + padrão AOCP",prompt:"Sobre manifestações da cultura popular pernambucana, assinale a alternativa correta.",options:["O frevo é manifestação exclusivamente rural, sem relação histórica com o carnaval urbano.","O maracatu e o frevo integram o patrimônio cultural e a identidade popular pernambucana.","A culinária não possui relevância na formação cultural do estado.","As festas populares pernambucanas surgiram apenas no século XXI.","Frevo e maracatu são manifestações originárias de outros estados e sem adaptação local."],answer:1,explanation:"Frevo e maracatu são manifestações centrais da cultura pernambucana."},
{id:"historia:7",subject:"historia",subjectName:"História de Pernambuco",topicIndex:7,topic:SUBJECTS[1].topics[7],source:"Autoral Cortex · materiais PMPE + padrão AOCP",prompt:"A respeito dos aspectos afro-brasileiros na formação de Pernambuco, assinale a alternativa correta.",options:["A presença africana teve papel restrito apenas à economia açucareira, sem impacto cultural.","A formação de quilombos representa uma das expressões de resistência da população negra escravizada.","As tradições religiosas afro-brasileiras não tiveram presença em Pernambuco.","A participação negra desapareceu após o período colonial.","A cultura pernambucana formou-se sem influência de matrizes africanas."],answer:1,explanation:"Quilombos foram espaços de resistência, e a influência africana é ampla na formação histórica e cultural pernambucana."},

{id:"rlm:0",subject:"rlm",subjectName:"Raciocínio Lógico",topicIndex:0,topic:SUBJECTS[2].topics[0],source:"Autoral Cortex · padrão AOCP/PMPE",context:"Considere as proposições: p: “A equipe realizou o patrulhamento.” q: “A ocorrência foi registrada.”",prompt:"A proposição “Se a equipe realizou o patrulhamento, então a ocorrência foi registrada” é falsa somente quando",options:["p e q são verdadeiras.","p é falsa e q é verdadeira.","p é verdadeira e q é falsa.","p e q são falsas.","q é verdadeira, independentemente de p."],answer:2,explanation:"Uma condicional p → q é falsa apenas no caso V → F."},
{id:"rlm:1",subject:"rlm",subjectName:"Raciocínio Lógico",topicIndex:1,topic:SUBJECTS[2].topics[1],source:"Autoral Cortex · padrão AOCP/PMPE",context:"Se a viatura A está em manutenção, então a viatura B será deslocada. A viatura B não foi deslocada.",prompt:"Do ponto de vista da lógica proposicional, é correto concluir que",options:["a viatura A está em manutenção.","a viatura A não está em manutenção.","a viatura B está em manutenção.","não é possível obter qualquer conclusão.","as duas viaturas estão em manutenção."],answer:1,explanation:"Aplicando modus tollens: se A → B e não B, então não A."},
{id:"rlm:2",subject:"rlm",subjectName:"Raciocínio Lógico",topicIndex:2,topic:SUBJECTS[2].topics[2],source:"Autoral Cortex · padrão AOCP/PMPE",context:"Em um curso, 42 policiais fizeram Treinamento A, 30 fizeram Treinamento B e 18 fizeram ambos. Todos os participantes fizeram pelo menos um dos dois treinamentos.",prompt:"Quantos policiais participaram do curso?",options:["54.","60.","72.","90.","126."],answer:0,explanation:"|A ∪ B| = 42 + 30 − 18 = 54."},
{id:"rlm:3",subject:"rlm",subjectName:"Raciocínio Lógico",topicIndex:3,topic:SUBJECTS[2].topics[3],source:"Autoral Cortex · padrão AOCP/PMPE",context:"Para uma equipe operacional serão escolhidos 3 policiais dentre 8 disponíveis, sem distinção de função entre os escolhidos.",prompt:"De quantas maneiras diferentes a equipe pode ser formada?",options:["24.","56.","112.","336.","512."],answer:1,explanation:"Trata-se de combinação: C(8,3)=56."},

{id:"informatica:0",subject:"informatica",subjectName:"Informática",topicIndex:0,topic:SUBJECTS[3].topics[0],source:"Autoral Cortex · padrão AOCP/PMPE",prompt:"Em relação aos conceitos de internet, intranet e extranet, assinale a alternativa correta.",options:["Intranet é necessariamente uma rede pública acessível sem autenticação.","Internet e intranet não podem utilizar os mesmos protocolos de comunicação.","Extranet pode disponibilizar, de forma controlada, recursos de uma organização a usuários externos autorizados.","A internet é administrada por um único servidor central mundial.","Intranet é sinônimo de rede local sem qualquer uso de tecnologias web."],answer:2,explanation:"A extranet estende acesso controlado a usuários externos e pode usar tecnologias semelhantes às da internet/intranet."},
{id:"informatica:1",subject:"informatica",subjectName:"Informática",topicIndex:1,topic:SUBJECTS[3].topics[1],source:"Autoral Cortex · padrão AOCP/PMPE",prompt:"Assinale a alternativa que apresenta corretamente a relação entre navegador e computação em nuvem.",options:["O navegador é um provedor de acesso à internet.","Serviços em nuvem podem ser acessados por navegador, mas o navegador não é, por si só, o serviço de nuvem.","Computação em nuvem exige que todos os dados permaneçam exclusivamente no computador local.","Navegadores não utilizam protocolos da internet.","Todo serviço web é necessariamente um serviço de armazenamento em nuvem."],answer:1,explanation:"O navegador é um cliente para acessar serviços; nuvem é um modelo de oferta de recursos computacionais pela rede."},
{id:"informatica:2",subject:"informatica",subjectName:"Informática",topicIndex:2,topic:SUBJECTS[3].topics[2],source:"Autoral Cortex · padrão AOCP/PMPE",context:"Um servidor recebe e-mail que imita a identidade visual de um banco e pede atualização urgente de senha por meio de um link.",prompt:"A situação descrita caracteriza, principalmente,",options:["fragmentação de disco.","phishing.","backup incremental.","criptografia simétrica.","virtualização."],answer:1,explanation:"Phishing usa fraude e engenharia social para obter credenciais ou induzir ações maliciosas."},
{id:"informatica:3",subject:"informatica",subjectName:"Informática",topicIndex:3,topic:SUBJECTS[3].topics[3],source:"Autoral Cortex · padrão AOCP/PMPE",prompt:"Sobre estratégias de backup, assinale a alternativa correta.",options:["Backup completo copia apenas os arquivos modificados desde o último backup.","Backup incremental copia, em regra, alterações desde o último backup realizado, completo ou incremental.","Backup diferencial nunca depende de um backup completo.","Restaurar dados torna desnecessária a existência de cópias de segurança.","Backup e sincronização são sempre conceitos equivalentes."],answer:1,explanation:"No incremental, cada execução considera as alterações desde o backup anterior."},
{id:"informatica:4",subject:"informatica",subjectName:"Informática",topicIndex:4,topic:SUBJECTS[3].topics[4],source:"Autoral Cortex · padrão AOCP/PMPE",prompt:"Assinale a alternativa correta sobre organização de arquivos e componentes de computadores.",options:["Memória RAM é meio de armazenamento permanente destinado a arquivamento de longo prazo.","Teclado e mouse são exemplos de dispositivos exclusivamente de saída.","Mover um arquivo entre pastas no mesmo sistema de arquivos necessariamente cria duas cópias independentes.","SSD é dispositivo de armazenamento; teclado é periférico de entrada.","Renomear um arquivo altera obrigatoriamente o seu conteúdo interno."],answer:3,explanation:"SSD armazena dados; teclado é periférico de entrada."},
{id:"informatica:5",subject:"informatica",subjectName:"Informática",topicIndex:5,topic:SUBJECTS[3].topics[5],source:"Autoral Cortex · padrão AOCP/PMPE",prompt:"No Windows 11, assinale a alternativa correta.",options:["O Explorador de Arquivos é usado somente para navegar na internet.","O Painel de Controle e o aplicativo Configurações podem oferecer acesso a ajustes do sistema.","O Prompt de Comando não permite execução de comandos textuais.","Arquivos excluídos são sempre destruídos de forma irrecuperável imediatamente.","Não é possível renomear pastas pelo Explorador de Arquivos."],answer:1,explanation:"Ambos fornecem acesso a configurações, ainda que com interfaces e escopos diferentes."},
{id:"informatica:6",subject:"informatica",subjectName:"Informática",topicIndex:6,topic:SUBJECTS[3].topics[6],source:"Autoral Cortex · padrão AOCP/PMPE",context:"Considere uma planilha em que as células B2:B6 contêm cinco valores numéricos.",prompt:"No Excel 2019 em português, qual fórmula calcula a média aritmética desses valores?",options:["=SOMA(B2:B6)/2","=MÉDIA(B2:B6)","=CONT.SE(B2:B6)","=SE(B2:B6)","=MÁXIMO(B2;B6;5)"],answer:1,explanation:"A função MÉDIA retorna a média aritmética dos valores do intervalo."},

{id:"constitucional:0",subject:"constitucional",subjectName:"Direito Constitucional",topicIndex:0,topic:SUBJECTS[4].topics[0],source:"Autoral Cortex · CF/88 + padrão AOCP/PMPE",prompt:"Nos termos da Constituição Federal, constitui fundamento da República Federativa do Brasil",options:["a erradicação da pobreza.","a garantia do desenvolvimento nacional.","a soberania.","a defesa da paz.","a redução das desigualdades regionais."],answer:2,explanation:"Soberania é fundamento do art. 1º. As demais alternativas apresentam objetivos ou princípios de relações internacionais."},
{id:"constitucional:1",subject:"constitucional",subjectName:"Direito Constitucional",topicIndex:1,topic:SUBJECTS[4].topics[1],source:"Autoral Cortex · CF/88 + padrão AOCP/PMPE",prompt:"Sobre direitos e garantias fundamentais, assinale a alternativa correta.",options:["O habeas corpus protege exclusivamente direito patrimonial.","O mandado de segurança destina-se a proteger liberdade de locomoção.","A Constituição assegura direitos individuais e coletivos e prevê remédios constitucionais para sua tutela.","Direitos sociais não integram o Título II da Constituição.","Direitos políticos não possuem natureza constitucional."],answer:2,explanation:"A CF/88 reúne direitos e garantias fundamentais no Título II e prevê instrumentos de tutela."},
{id:"constitucional:2",subject:"constitucional",subjectName:"Direito Constitucional",topicIndex:2,topic:SUBJECTS[4].topics[2],source:"Autoral Cortex · CF/88 + padrão AOCP/PMPE",prompt:"Acerca da organização do Estado e da Administração Pública, assinale a alternativa correta.",options:["Os Estados-membros possuem soberania própria e podem se separar da Federação.","União, Estados, Distrito Federal e Municípios possuem competências constitucionalmente distribuídas.","Municípios não integram a organização político-administrativa brasileira.","Militares dos Estados são disciplinados exclusivamente por normas municipais.","A Administração Pública não está sujeita a princípios constitucionais."],answer:1,explanation:"A CF distribui competências entre os entes federativos, que possuem autonomia, não soberania."},
{id:"constitucional:3",subject:"constitucional",subjectName:"Direito Constitucional",topicIndex:3,topic:SUBJECTS[4].topics[3],source:"Autoral Cortex · CF/88 + padrão AOCP/PMPE",prompt:"Nos termos da Constituição Federal, os Poderes da União são",options:["Legislativo, Executivo e Ministério Público.","Executivo, Judiciário e Defensoria Pública.","Legislativo, Executivo e Judiciário, independentes e harmônicos entre si.","Legislativo e Executivo apenas.","Judiciário, Ministério Público e Tribunal de Contas."],answer:2,explanation:"É a redação essencial do art. 2º da Constituição."},
{id:"constitucional:4",subject:"constitucional",subjectName:"Direito Constitucional",topicIndex:4,topic:SUBJECTS[4].topics[4],source:"Autoral Cortex · CF/88 + padrão AOCP/PMPE",prompt:"A respeito da defesa do Estado e das instituições democráticas, assinale a alternativa correta.",options:["Estado de defesa e estado de sítio são institutos idênticos e possuem os mesmos pressupostos.","A Constituição disciplina mecanismos excepcionais destinados à preservação ou restabelecimento da ordem constitucional em hipóteses específicas.","A segurança pública não possui previsão constitucional.","As Forças Armadas integram o Poder Judiciário.","Nenhuma restrição excepcional a direitos pode ser prevista constitucionalmente."],answer:1,explanation:"A CF prevê estado de defesa e estado de sítio com hipóteses, procedimentos e limites próprios."},
{id:"constitucional:5",subject:"constitucional",subjectName:"Direito Constitucional",topicIndex:5,topic:SUBJECTS[4].topics[5],source:"Autoral Cortex · padrão AOCP/PMPE",prompt:"No estudo de súmulas e jurisprudência dominante dos Tribunais Superiores para concursos, é correto afirmar que",options:["entendimentos jurisprudenciais podem ser ignorados quando o edital os menciona expressamente.","súmula e texto constitucional são sempre a mesma fonte normativa.","a leitura deve ser feita em conjunto com a legislação vigente e com a delimitação do edital.","toda decisão judicial isolada possui efeito vinculante geral.","jurisprudência nunca sofre alteração."],answer:2,explanation:"O edital cobra entendimento dominante e legislação relacionada; a atualização é essencial."},

{id:"dh:0",subject:"dh",subjectName:"Direitos Humanos e Legislação Extravagante",topicIndex:0,topic:SUBJECTS[5].topics[0],source:"Autoral Cortex · materiais PMPE + legislação",prompt:"Sobre a teoria geral dos direitos humanos, assinale a alternativa correta.",options:["Direitos humanos existem apenas quando concedidos individualmente pelo Estado.","A dignidade da pessoa humana é referência central na fundamentação contemporânea dos direitos humanos.","Universalidade significa que direitos humanos pertencem somente aos nacionais de cada Estado.","Indivisibilidade estabelece hierarquia rígida entre direitos civis e direitos sociais.","Direitos humanos e direitos fundamentais são expressões absolutamente idênticas em qualquer contexto."],answer:1,explanation:"A dignidade humana é fundamento central, e universalidade/indivisibilidade afastam as demais afirmações."},
{id:"dh:1",subject:"dh",subjectName:"Direitos Humanos e Legislação Extravagante",topicIndex:1,topic:SUBJECTS[5].topics[1],source:"Autoral Cortex · materiais PMPE + legislação",prompt:"A respeito das chamadas dimensões ou gerações de direitos humanos, assinale a alternativa correta.",options:["A segunda dimensão eliminou os direitos de primeira dimensão.","A classificação é didática e as diferentes dimensões coexistem.","Direitos de terceira dimensão são exclusivamente direitos patrimoniais individuais.","Direitos sociais pertencem apenas à primeira dimensão.","A evolução histórica impede que novos direitos sejam reconhecidos."],answer:1,explanation:"As dimensões são uma classificação didática e não se substituem cronologicamente."},
{id:"dh:2",subject:"dh",subjectName:"Direitos Humanos e Legislação Extravagante",topicIndex:2,topic:SUBJECTS[5].topics[2],source:"Autoral Cortex · CF/88 + materiais PMPE",prompt:"Nos termos do art. 5º, §3º, da Constituição Federal, tratados e convenções internacionais sobre direitos humanos aprovados em cada Casa do Congresso Nacional, em dois turnos, por três quintos dos votos dos respectivos membros serão equivalentes",options:["às leis ordinárias.","às leis complementares.","às emendas constitucionais.","a decretos regulamentares.","a resoluções administrativas."],answer:2,explanation:"É a regra expressa do art. 5º, §3º, da CF/88."},
{id:"dh:3",subject:"dh",subjectName:"Direitos Humanos e Legislação Extravagante",topicIndex:3,topic:SUBJECTS[5].topics[3],source:"Autoral Cortex · DUDH",prompt:"De acordo com a Declaração Universal dos Direitos Humanos, assinale a alternativa correta.",options:["A dignidade é atribuída apenas a pessoas com cidadania reconhecida.","Todos os seres humanos nascem livres e iguais em dignidade e direitos.","A liberdade de pensamento pode ser abolida por decisão administrativa comum.","A proteção contra tortura não aparece entre os direitos proclamados.","A igualdade perante a lei depende de nacionalidade específica."],answer:1,explanation:"A DUDH afirma a igualdade em dignidade e direitos como princípio fundamental."},
{id:"dh:4",subject:"dh",subjectName:"Direitos Humanos e Legislação Extravagante",topicIndex:4,topic:SUBJECTS[5].topics[4],source:"Autoral Cortex · CADH/Decreto 678/1992",prompt:"A Convenção Americana sobre Direitos Humanos, conhecida como Pacto de San José da Costa Rica,",options:["integra o sistema interamericano de proteção dos direitos humanos.","é norma exclusiva da União Europeia.","não foi promulgada no Brasil.","trata apenas de direitos trabalhistas.","elimina a competência de todos os tribunais nacionais."],answer:0,explanation:"A Convenção integra o sistema interamericano e foi promulgada no Brasil pelo Decreto 678/1992."},
{id:"dh:5",subject:"dh",subjectName:"Direitos Humanos e Legislação Extravagante",topicIndex:5,topic:SUBJECTS[5].topics[5],source:"Autoral Cortex · ECA",context:"Durante uma ocorrência, um adolescente é apreendido em situação de flagrante de ato infracional.",prompt:"À luz do ECA, assinale a alternativa correta.",options:["O adolescente não possui garantias individuais durante a apreensão.","A apreensão deve observar as garantias legais previstas no Estatuto e a autoridade competente deve ser comunicada conforme a lei.","O Conselho Tutelar substitui obrigatoriamente a autoridade judiciária em qualquer ato infracional.","O ECA não disciplina a atuação policial em situações envolvendo adolescentes.","A condição de adolescente autoriza tratamento degradante para obtenção de confissão."],answer:1,explanation:"O ECA prevê garantias específicas e disciplina procedimentos relacionados à apreensão e apresentação."},
{id:"dh:6",subject:"dh",subjectName:"Direitos Humanos e Legislação Extravagante",topicIndex:6,topic:SUBJECTS[5].topics[6],source:"Autoral Cortex · Lei 13.869/2019",prompt:"Sobre a Lei de Abuso de Autoridade (Lei nº 13.869/2019), assinale a alternativa correta.",options:["Todo erro funcional configura automaticamente crime de abuso de autoridade.","A lei tipifica condutas praticadas por agente público e exige a presença dos elementos previstos em cada tipo penal.","A lei se aplica apenas a magistrados.","A responsabilização penal independe de conduta prevista em lei.","A lei revogou todas as garantias funcionais dos agentes públicos."],answer:1,explanation:"A configuração do crime depende da conduta tipificada e dos requisitos legais."},
{id:"dh:7",subject:"dh",subjectName:"Direitos Humanos e Legislação Extravagante",topicIndex:7,topic:SUBJECTS[5].topics[7],source:"Autoral Cortex · Lei 9.455/1997",prompt:"Nos termos da Lei nº 9.455/1997, a tortura",options:["é contravenção penal.","é crime disciplinado em lei específica, com hipóteses e consequências próprias.","somente pode ser praticada por agente público.","admite fiança obrigatoriamente em qualquer hipótese.","não possui relação com sofrimento físico ou mental."],answer:1,explanation:"A Lei 9.455/1997 define crimes de tortura e não restringe todos os tipos a agentes públicos."},
{id:"dh:8",subject:"dh",subjectName:"Direitos Humanos e Legislação Extravagante",topicIndex:8,topic:SUBJECTS[5].topics[8],source:"Autoral Cortex · Lei 11.340/2006",context:"Uma mulher relata violência praticada por companheiro no ambiente doméstico e procura atendimento policial.",prompt:"À luz da Lei Maria da Penha, assinale a alternativa correta.",options:["A lei se aplica somente quando houver casamento civil.","A violência doméstica e familiar pode assumir diferentes formas, e a lei prevê mecanismos específicos de proteção.","A lei impede qualquer medida protetiva de urgência.","A atuação policial somente pode ocorrer após sentença judicial definitiva.","Violência psicológica não é abrangida pela proteção legal."],answer:1,explanation:"A Lei 11.340/2006 abrange diversas formas de violência e prevê medidas protetivas e procedimentos específicos."},
{id:"dh:9",subject:"dh",subjectName:"Direitos Humanos e Legislação Extravagante",topicIndex:9,topic:SUBJECTS[5].topics[9],source:"Autoral Cortex · Lei 7.716/1989",prompt:"A Lei nº 7.716/1989",options:["trata exclusivamente de crimes patrimoniais.","define crimes resultantes de discriminação ou preconceito nas hipóteses previstas em seu texto.","revoga o princípio constitucional da igualdade.","aplica-se somente a relações de trabalho.","não prevê condutas relacionadas a preconceito racial."],answer:1,explanation:"A lei define crimes resultantes de discriminação ou preconceito conforme seu âmbito normativo."},
{id:"dh:10",subject:"dh",subjectName:"Direitos Humanos e Legislação Extravagante",topicIndex:10,topic:SUBJECTS[5].topics[10],source:"Autoral Cortex · Lei 9.605/1998",prompt:"Sobre a Lei de Crimes Ambientais (Lei nº 9.605/1998), assinale a alternativa correta.",options:["A lei prevê apenas sanções civis.","A lei reúne sanções penais e administrativas derivadas de condutas lesivas ao meio ambiente.","Pessoas jurídicas jamais podem responder por infrações ambientais.","A legislação ambiental não alcança condutas contra a fauna.","Todo dano ambiental é mera infração administrativa, nunca crime."],answer:1,explanation:"A lei disciplina sanções penais e administrativas e alcança diversos bens ambientais."},
{id:"dh:11",subject:"dh",subjectName:"Direitos Humanos e Legislação Extravagante",topicIndex:11,topic:SUBJECTS[5].topics[11],source:"Autoral Cortex · Lei 8.072/1990",prompt:"Em relação à Lei dos Crimes Hediondos (Lei nº 8.072/1990), assinale a alternativa correta.",options:["A classificação de crime hediondo depende apenas da opinião da autoridade policial.","A lei estabelece rol e tratamento jurídico específico para os crimes nela previstos.","Todo crime doloso é automaticamente hediondo.","A lei não produz qualquer efeito sobre execução penal.","Hediondez é criada por decreto estadual."],answer:1,explanation:"A hediondez decorre da lei federal e gera regime jurídico específico."},
{id:"dh:12",subject:"dh",subjectName:"Direitos Humanos e Legislação Extravagante",topicIndex:12,topic:SUBJECTS[5].topics[12],source:"Autoral Cortex · Lei 11.343/2006",prompt:"A Lei nº 11.343/2006, conhecida como Lei de Drogas,",options:["disciplina apenas o uso medicinal de substâncias.","institui o SISNAD e disciplina medidas de prevenção, atenção e repressão a condutas relacionadas a drogas.","revogou toda distinção entre usuário e traficante.","é aplicável somente a militares.","não contém tipos penais."],answer:1,explanation:"A lei institui o SISNAD e disciplina políticas e crimes relacionados a drogas."},
{id:"dh:13",subject:"dh",subjectName:"Direitos Humanos e Legislação Extravagante",topicIndex:13,topic:SUBJECTS[5].topics[13],source:"Autoral Cortex · Lei Estadual 6.783/1974",prompt:"A Lei Estadual nº 6.783/1974 é relevante para o concurso da PMPE porque",options:["institui o Código Penal brasileiro.","dispõe sobre o Estatuto dos Policiais Militares do Estado de Pernambuco.","regula exclusivamente servidores civis federais.","trata apenas da organização municipal do Recife.","substitui integralmente a Constituição Federal."],answer:1,explanation:"É o Estatuto dos Policiais Militares do Estado de Pernambuco."},
{id:"dh:14",subject:"dh",subjectName:"Direitos Humanos e Legislação Extravagante",topicIndex:14,topic:SUBJECTS[5].topics[14],source:"Autoral Cortex · Lei 10.741/2003",prompt:"Nos termos do Estatuto da Pessoa Idosa, considera-se pessoa idosa, para os fins da lei, aquela com idade igual ou superior a",options:["55 anos.","60 anos.","62 anos.","65 anos em qualquer hipótese.","70 anos."],answer:1,explanation:"A Lei 10.741/2003 considera idosa a pessoa com 60 anos ou mais."},
{id:"dh:15",subject:"dh",subjectName:"Direitos Humanos e Legislação Extravagante",topicIndex:15,topic:SUBJECTS[5].topics[15],source:"Autoral Cortex · Lei 12.852/2013",prompt:"O Estatuto da Juventude (Lei nº 12.852/2013) estabelece",options:["direitos dos jovens e diretrizes de políticas públicas de juventude.","normas exclusivamente penais militares.","apenas regras de direito eleitoral.","somente deveres, sem previsão de direitos.","normas restritas a pessoas com mais de 60 anos."],answer:0,explanation:"A lei institui o Estatuto da Juventude e dispõe sobre direitos dos jovens e políticas públicas."},
{id:"dh:16",subject:"dh",subjectName:"Direitos Humanos e Legislação Extravagante",topicIndex:16,topic:SUBJECTS[5].topics[16],source:"Autoral Cortex · padrão AOCP/PMPE",prompt:"Para a preparação em Direitos Humanos e Legislação Extravagante, o edital também exige súmulas, jurisprudência dominante e legislação relacionada. Nessa perspectiva, assinale a alternativa correta.",options:["Somente o texto literal das leis pode ser cobrado, ainda que o edital mencione jurisprudência.","Entendimentos dos Tribunais Superiores devem ser estudados de forma atualizada e relacionados aos temas expressamente previstos.","Qualquer decisão isolada de primeiro grau equivale a súmula vinculante.","Jurisprudência é imutável.","Atualizações legislativas posteriores ao edital nunca podem afetar a interpretação da matéria."],answer:1,explanation:"Quando o edital inclui jurisprudência dominante, é necessário estudar entendimentos atualizados e pertinentes aos temas."}
];
function esc(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));}
const extras=Array.isArray(window.PMPE_EXTRA_QUESTIONS)?window.PMPE_EXTRA_QUESTIONS:[];
const existingIds=new Set(BANK.map(q=>q.id));
for(const candidate of extras){
  const subject=SUBJECTS.find(s=>s.key===candidate.subject);
  if(!subject||!Number.isInteger(candidate.topicIndex)||candidate.topicIndex<0||candidate.topicIndex>=subject.topics.length)continue;
  if(!candidate.id||existingIds.has(candidate.id)||!Array.isArray(candidate.options)||candidate.options.length!==5||new Set(candidate.options).size!==5||!Number.isInteger(candidate.answer)||candidate.answer<0||candidate.answer>4||!candidate.prompt||!candidate.explanation)continue;
  existingIds.add(candidate.id);
  BANK.push({...candidate,subjectName:subject.name,topic:subject.topics[candidate.topicIndex]});
}
let qstate={};
try{qstate=JSON.parse(localStorage.getItem(QSTORE)||"{}")||{};}catch(e){}
function saveQ(){try{localStorage.setItem(QSTORE,JSON.stringify(qstate));}catch(e){}}
function setTab(name){
  document.querySelectorAll("[data-pmpe-tab]").forEach(b=>b.classList.toggle("active",b.dataset.pmpeTab===name));
  document.querySelectorAll("[data-pmpe-panel]").forEach(p=>p.hidden=p.dataset.pmpePanel!==name);
  document.querySelectorAll(".pmpe-course,.pmpe-week,.pmpe-plan").forEach(p=>p.hidden=name!=="plano");
  if(name==="questoes"){populateQuestionSelectors();const amount=document.getElementById("pmpeQuestionAmount");if(amount)amount.value="0";}
  window.scrollTo({top:0,behavior:"smooth"});
}
document.querySelectorAll("[data-pmpe-tab]").forEach(b=>b.addEventListener("click",()=>setTab(b.dataset.pmpeTab)));
window.PMPEOpenQuestions=function(key){
  setTab("questoes");
  const [subject,idx]=String(key).split(":");
  const ss=document.getElementById("pmpeQuestionSubject"),ts=document.getElementById("pmpeQuestionTopic");
  if(ss){ss.value=subject;populateTopics();if(ts)ts.value=idx;}
  const amount=document.getElementById("pmpeQuestionAmount");if(amount)amount.value="0";
  startQuestions();
};
function populateQuestionSelectors(){
  const ss=document.getElementById("pmpeQuestionSubject");
  if(!ss||ss.dataset.ready)return;
  ss.innerHTML='<option value="all">Todas as matérias</option>'+SUBJECTS.map(s=>'<option value="'+s.key+'">'+esc(s.name)+'</option>').join("");
  ss.dataset.ready="1";ss.addEventListener("change",populateTopics);populateTopics();
}
function populateTopics(){
  const ss=document.getElementById("pmpeQuestionSubject"),ts=document.getElementById("pmpeQuestionTopic");if(!ss||!ts)return;
  const s=SUBJECTS.find(x=>x.key===ss.value);
  ts.innerHTML='<option value="all">Todos os tópicos ('+BANK.filter(q=>!s||q.subject===s.key).length+')</option>'+(s?s.topics.map((t,i)=>{const count=BANK.filter(q=>q.subject===s.key&&q.topicIndex===i).length;return '<option value="'+i+'">'+esc(t)+' ('+count+')</option>';}).join(""):"");
}
function shuffledQuestion(q){
  const items=q.options.map((text,index)=>({text,index}));
  for(let i=items.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[items[i],items[j]]=[items[j],items[i]];}
  return {...q,options:items.map(x=>x.text),answer:items.findIndex(x=>x.index===q.answer)};
}
function selectedQuestions(){
  const subject=document.getElementById("pmpeQuestionSubject")?.value||"all";
  const topic=document.getElementById("pmpeQuestionTopic")?.value||"all";
  let list=BANK.filter(q=>(subject==="all"||q.subject===subject)&&(topic==="all"||String(q.topicIndex)===topic));
  for(let i=list.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[list[i],list[j]]=[list[j],list[i]];}
  const n=Number(document.getElementById("pmpeQuestionAmount")?.value||0);
  if(n>0)list=list.slice(0,n);
  return list.map(shuffledQuestion);
}
let session=[],current=0,answers={};
function startQuestions(){
  session=selectedQuestions();current=0;answers={};renderQuestion();
}
function renderQuestion(){
  const host=document.getElementById("pmpeQuestionRunner");if(!host)return;
  if(!session.length){host.innerHTML='<div class="pmpe-empty">Nenhuma questão encontrada para este filtro.</div>';return;}
  if(current>=session.length){const hits=session.reduce((n,q)=>n+(answers[q.id]===q.answer?1:0),0);qstate.sessions=(qstate.sessions||0)+1;qstate.answered=(qstate.answered||0)+session.length;qstate.correct=(qstate.correct||0)+hits;saveQ();host.innerHTML='<div class="pmpe-question-summary"><article><span>Resultado</span><strong>'+hits+'/'+session.length+'</strong></article><article><span>Aproveitamento</span><strong>'+Math.round(hits/session.length*100)+'%</strong></article><article><span>Sessões PMPE</span><strong>'+qstate.sessions+'</strong></article></div><div class="pmpe-question-nav"><button type="button" id="pmpeReviewAgain">Refazer</button><button type="button" id="pmpeBackTopics">Escolher outro tópico</button></div>';document.getElementById("pmpeReviewAgain")?.addEventListener("click",startQuestions);return;}
  const q=session[current],chosen=answers[q.id],answered=chosen!==undefined;
  host.innerHTML='<article class="pmpe-question-card"><div class="pmpe-question-meta"><span>'+esc(q.subjectName)+' · '+esc(q.topic)+'</span><span>'+(current+1)+' / '+session.length+'</span></div>'+(q.context?'<div class="pmpe-question-context">'+esc(q.context).replace(/\\n/g,"<br>")+'</div>':"")+'<h3>'+esc(q.prompt||("Assinale a alternativa correta sobre "+q.topic+"."))+'</h3><div class="pmpe-answer-list">'+q.options.map((o,i)=>'<button class="pmpe-answer '+(answered?(i===q.answer?"correct":i===chosen?"wrong":""):"")+'" type="button" data-answer="'+i+'" '+(answered?"disabled":"")+'><b>'+"ABCDE"[i]+'</b><span>'+esc(o)+'</span></button>').join("")+'</div>'+(answered?'<div class="pmpe-question-feedback"><strong>'+(chosen===q.answer?"Correto.":"Resposta correta: "+"ABCDE"[q.answer]+".")+'</strong><br>'+esc(q.explanation)+'<br><small>'+esc(q.source)+'</small></div>':"")+'<div class="pmpe-question-nav"><button type="button" id="pmpePrevQuestion" '+(current===0?"disabled":"")+'>Anterior</button><button type="button" id="pmpeNextQuestion">'+(answered?(current===session.length-1?"Finalizar":"Próxima"):"Responder")+'</button></div></article>';
  host.querySelectorAll("[data-answer]").forEach(b=>b.addEventListener("click",()=>{answers[q.id]=Number(b.dataset.answer);renderQuestion();}));
  document.getElementById("pmpePrevQuestion")?.addEventListener("click",()=>{if(current>0){current--;renderQuestion();}});
  document.getElementById("pmpeNextQuestion")?.addEventListener("click",()=>{if(answers[q.id]===undefined)return;current++;renderQuestion();});
}
document.getElementById("pmpeStartQuestions")?.addEventListener("click",startQuestions);
document.querySelectorAll("[data-open-bank]").forEach(b=>b.addEventListener("click",()=>{setTab("questoes");populateQuestionSelectors();document.getElementById("pmpeQuestionSubject").value="all";populateTopics();startQuestions();}));

let pdfjs=null,pdfDoc=null,pdfPage=1,pdfDocName="sim2026",renderToken=0;
async function ensurePdf(){
  if(pdfjs)return pdfjs;
  pdfjs=await import("https://cdn.jsdelivr.net/npm/pdfjs-dist@4.10.38/build/pdf.min.mjs");
  pdfjs.GlobalWorkerOptions.workerSrc="https://cdn.jsdelivr.net/npm/pdfjs-dist@4.10.38/build/pdf.worker.min.mjs";
  return pdfjs;
}
async function openPdf(doc,title){
  const reader=document.getElementById("pmpePdfReader");if(!reader)return;
  reader.hidden=false;pdfDocName=doc;pdfPage=1;document.getElementById("pmpeReaderTitle").textContent=title;document.getElementById("pmpeReaderLabel").textContent=doc==="gabarito2026"?"GABARITO":"SIMULADO";
  reader.scrollIntoView({behavior:"smooth",block:"start"});
  const lib=await ensurePdf();pdfDoc=await lib.getDocument({url:"/api/pmpe/pdf?doc="+encodeURIComponent(doc),withCredentials:true}).promise;await renderPdfPage();
}
async function renderPdfPage(){
  if(!pdfDoc)return;const token=++renderToken,page=await pdfDoc.getPage(pdfPage);if(token!==renderToken)return;
  const stage=document.getElementById("pmpeCanvasStage"),canvas=document.getElementById("pmpePdfCanvas"),ctx=canvas.getContext("2d");
  const base=page.getViewport({scale:1});const maxW=Math.min(stage.clientWidth-20,1050);const scale=Math.max(.6,Math.min(2,maxW/base.width));const vp=page.getViewport({scale});
  canvas.width=Math.floor(vp.width*devicePixelRatio);canvas.height=Math.floor(vp.height*devicePixelRatio);canvas.style.width=Math.floor(vp.width)+"px";canvas.style.height=Math.floor(vp.height)+"px";
  ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);await page.render({canvasContext:ctx,viewport:vp}).promise;
  document.getElementById("pmpeReaderPage").textContent=pdfPage+" / "+pdfDoc.numPages;
}
document.querySelectorAll("[data-open-sim]").forEach(b=>b.addEventListener("click",()=>openPdf("sim2026","Simulado gratuito EBN · PMPE 2026").catch(()=>alert("Não foi possível abrir o caderno agora."))));
document.getElementById("pmpeReaderPrev")?.addEventListener("click",()=>{if(pdfDoc&&pdfPage>1){pdfPage--;renderPdfPage();}});
document.getElementById("pmpeReaderNext")?.addEventListener("click",()=>{if(pdfDoc&&pdfPage<pdfDoc.numPages){pdfPage++;renderPdfPage();}});
document.getElementById("pmpeReaderClose")?.addEventListener("click",()=>{document.getElementById("pmpePdfReader").hidden=true;pdfDoc=null;});
document.getElementById("pmpeOpenAnswerSheet")?.addEventListener("click",()=>openPdf(pdfDocName==="gabarito2026"?"sim2026":"gabarito2026",pdfDocName==="gabarito2026"?"Simulado gratuito EBN · PMPE 2026":"Gabarito · PMPE 2026"));
let touchX=null;const stage=document.getElementById("pmpeCanvasStage");stage?.addEventListener("pointerdown",e=>{touchX=e.clientX;});stage?.addEventListener("pointerup",e=>{if(touchX===null)return;const d=e.clientX-touchX;touchX=null;if(Math.abs(d)<60)return;if(d<0&&pdfDoc&&pdfPage<pdfDoc.numPages){pdfPage++;renderPdfPage();}if(d>0&&pdfDoc&&pdfPage>1){pdfPage--;renderPdfPage();}});

const CALSTORE="cortex_pmpe_2026_calendar";
let calDate=new Date();calDate=new Date(calDate.getFullYear(),calDate.getMonth(),1);
function calendarPlan(){
  const topics=[];SUBJECTS.forEach(s=>s.topics.forEach((topic,i)=>topics.push({key:s.key+":"+i,subject:s.name,topic})));
  const start=new Date(2026,9,7), exam=new Date(2027,1,21), studyDays=[];
  for(let d=new Date(start);d<exam;d.setDate(d.getDate()+1)){const day=d.getDay();if(day!==0)studyDays.push(new Date(d));}
  const plan={};
  topics.forEach((t,i)=>{
    const d=studyDays[Math.floor(i*studyDays.length/topics.length)]||studyDays[i%studyDays.length];
    const k=[d.getFullYear(),String(d.getMonth()+1).padStart(2,"0"),String(d.getDate()).padStart(2,"0")].join("-");
    (plan[k]||(plan[k]=[])).push({...t,type:"study"});
    [1,7,30].forEach(delta=>{const r=new Date(d);r.setDate(r.getDate()+delta);if(r<exam){const rk=[r.getFullYear(),String(r.getMonth()+1).padStart(2,"0"),String(r.getDate()).padStart(2,"0")].join("-");(plan[rk]||(plan[rk]=[])).push({...t,type:"review"});}});
  });
  return plan;
}
const CALPLAN=calendarPlan();
function renderCalendar(){
  const host=document.getElementById("pmpeCalendarGrid"),label=document.getElementById("pmpeCalendarLabel");if(!host||!label)return;
  const y=calDate.getFullYear(),m=calDate.getMonth();label.textContent=calDate.toLocaleDateString("pt-BR",{month:"long",year:"numeric"});
  const first=new Date(y,m,1),last=new Date(y,m+1,0),start=(first.getDay()+6)%7;
  const today=new Date(),names=["SEG","TER","QUA","QUI","SEX","SÁB","DOM"];
  let html=names.map(n=>'<div class="pmpe-cal-weekday">'+n+'</div>').join("");
  for(let i=0;i<start;i++)html+='<div class="pmpe-cal-day muted"></div>';
  for(let day=1;day<=last.getDate();day++){
    const d=new Date(y,m,day),key=[y,String(m+1).padStart(2,"0"),String(day).padStart(2,"0")].join("-"),items=CALPLAN[key]||[];
    const isToday=d.toDateString()===today.toDateString(),hasStudy=items.some(x=>x.type==="study"),hasReview=items.some(x=>x.type==="review");
    html+='<button type="button" class="pmpe-cal-day '+(isToday?"today ":"")+(items.length?"has-events ":"")+'" data-cal-day="'+key+'"><span class="pmpe-cal-num">'+day+'</span><span class="pmpe-cal-dots">'+(hasStudy?'<i class="study"></i>':"")+(hasReview?'<i class="review"></i>':"")+'</span>'+(items.length?'<small>'+items.length+' tarefa'+(items.length>1?"s":"")+'</small>':"")+'</button>';
  }
  host.innerHTML=html;
  host.querySelectorAll("[data-cal-day]").forEach(b=>b.addEventListener("click",()=>renderCalendarDay(b.dataset.calDay)));
}
function renderCalendarDay(key){
  const detail=document.getElementById("pmpeCalendarDetail");if(!detail)return;const items=CALPLAN[key]||[];
  const [y,m,d]=key.split("-");const title=new Date(Number(y),Number(m)-1,Number(d)).toLocaleDateString("pt-BR",{weekday:"long",day:"2-digit",month:"long"});
  detail.innerHTML='<div class="pmpe-cal-detail-head"><strong>'+title+'</strong><span>'+items.length+' tarefa'+(items.length!==1?"s":"")+'</span></div>'+(items.length?items.map(x=>'<button type="button" class="pmpe-cal-task '+x.type+'" data-cal-topic="'+x.key+'"><span>'+(x.type==="study"?"Estudo":"Revisão")+'</span><strong>'+esc(x.subject)+'</strong><small>'+esc(x.topic)+'</small></button>').join(""):'<div class="pmpe-cal-empty">Dia livre no cronograma.</div>');
  detail.querySelectorAll("[data-cal-topic]").forEach(b=>b.addEventListener("click",()=>{setTab("plano");const [subject]=b.dataset.calTopic.split(":");const filter=document.querySelector('[data-filter="'+subject+'"]');if(filter)filter.click();setTimeout(()=>document.querySelector('[data-topic-key="'+CSS.escape(b.dataset.calTopic)+'"]')?.scrollIntoView({behavior:"smooth",block:"center"}),80);}));
}
document.getElementById("pmpeCalendarPrev")?.addEventListener("click",()=>{calDate.setMonth(calDate.getMonth()-1);renderCalendar();});
document.getElementById("pmpeCalendarNext")?.addEventListener("click",()=>{calDate.setMonth(calDate.getMonth()+1);renderCalendar();});
document.getElementById("pmpeCalendarToday")?.addEventListener("click",()=>{const n=new Date();calDate=new Date(n.getFullYear(),n.getMonth(),1);renderCalendar();renderCalendarDay([n.getFullYear(),String(n.getMonth()+1).padStart(2,"0"),String(n.getDate()).padStart(2,"0")].join("-"));});
renderCalendar();
populateQuestionSelectors();
})();
